/**
 * GENERATED by scripts/calibrate-threshold.ts -- do not edit by hand.
 *
 * The similarity threshold tier 2 runs against, and the measurement it came from. Hand
 * editing this file would produce a number with no run behind it, which is what FR-016
 * forbids and what docs/DECISIONS.md's 2026-08-11 correction is the precedent for.
 */

/** Null when the calibration found no separation; tier 2 must then resolve nothing. */
export const SIMILARITY_THRESHOLD: number | null = null;

export const CALIBRATION = {
  calibratedAt: '2026-08-22T00:10:05.522Z',
  separated: false,
  matchingP5: 0.1921,
  nonMatchingP95: 0.5092,
  baseline: "phrases drawn from each concept's own source material (non-preamble chunks, concept names masked), scored against the stored concept vectors; the non-matching baseline is the same phrases scored against a different concept. Independent of concept_terms, which tier 1 matches against. This is a floor: a concept that cannot be recognised from its own words will not be rescued by alternative phrasing, while success here says nothing about whether real job-description wording reaches the right concept.",
  record: 'docs/calibration/resolve-threshold.json',
} as const;
