/**
 * The generated module tier 2 imports. It exists so the number the resolver runs against
 * and the number the record reports cannot drift: there is one place either can come
 * from, and it is regenerated by the same run that measured it (SC-006).
 */
export function calibrationModule(record: {
  calibratedAt: string;
  threshold: number | null;
  separated: boolean;
  baseline: string;
  matching: { p5: number | null };
  nonMatching: { p95: number | null };
}): string {
  const threshold = record.threshold === null ? 'null' : record.threshold.toFixed(4);
  return `/**
 * GENERATED by scripts/calibrate-threshold.ts -- do not edit by hand.
 *
 * The similarity threshold tier 2 runs against, and the measurement it came from. Hand
 * editing this file would produce a number with no run behind it, which is what FR-016
 * forbids and what docs/DECISIONS.md's 2026-08-11 correction is the precedent for.
 */

/** Null when the calibration found no separation; tier 2 must then resolve nothing. */
export const SIMILARITY_THRESHOLD: number | null = ${threshold};

export const CALIBRATION = {
  calibratedAt: '${record.calibratedAt}',
  separated: ${record.separated},
  matchingP5: ${record.matching.p5 ?? 'null'},
  nonMatchingP95: ${record.nonMatching.p95 ?? 'null'},
  baseline: ${JSON.stringify(record.baseline)},
  record: 'docs/calibration/resolve-threshold.json',
} as const;
`;
}
