#!/usr/bin/env python3
"""Structure probe (task D): stats only, no classification into a taxonomy.

For each source (file list taken from its corpus/_meta/manifest/{id}.jsonl —
i.e. exactly what task C/B left as citable content, no re-globbing raw/):
  1. every H2 heading text + occurrence count, sorted by frequency
     ("## " markdown syntax for .md/.mdx files; <h2> tag text for .html files
     — html sources were fetched as raw, unconverted HTML, so their
     "sections" only exist as real markup, not markdown syntax)
  2. file count, average file length (chars), average H2-heading count per file
  3. a structured-vs-prose judgement, by heuristic: if a small set of H2
     headings each appear in a large share of that source's files, call it
     "structured" (fixed-section docs like a pattern catalog); otherwise
     "prose" (tradeoffs embedded in running text, no dedicated section).

Deliberately does NOT: split into sections, build a section-map, assign a
canonical taxonomy across sources, or touch the database/embeddings.

Writes corpus/reports/structure-probe.md.
"""
import json
import re
import statistics
from collections import Counter
from pathlib import Path

from bs4 import BeautifulSoup

ROOT = Path(__file__).resolve().parents[2]
CORPUS = ROOT / "corpus"
MANIFEST_DIR = CORPUS / "_meta" / "manifest"
REPORT_PATH = CORPUS / "reports" / "structure-probe.md"

H2_RE = re.compile(r"^##(?!#)\s*(.+?)\s*$", re.MULTILINE)

# A source counts as "structured" if at least this many distinct H2 headings
# each appear in at least this share of the source's files.
STRUCTURED_MIN_HEADINGS = 2
STRUCTURED_MIN_FILE_SHARE = 0.30


def extract_headings(path: Path) -> list[str]:
    if path.suffix.lower() in (".md", ".mdx"):
        text = path.read_text(encoding="utf-8", errors="replace")
        return [h.strip() for h in H2_RE.findall(text)]
    if path.suffix.lower() in (".html", ".htm"):
        html = path.read_text(encoding="utf-8", errors="replace")
        soup = BeautifulSoup(html, "html.parser")
        return [h.get_text(" ", strip=True) for h in soup.find_all("h2")]
    return []


def file_length(path: Path) -> int:
    if path.suffix.lower() in (".html", ".htm"):
        html = path.read_text(encoding="utf-8", errors="replace")
        return len(BeautifulSoup(html, "html.parser").get_text(" ", strip=True))
    return len(path.read_text(encoding="utf-8", errors="replace"))


def probe_source(source_id: str) -> dict:
    manifest_path = MANIFEST_DIR / f"{source_id}.jsonl"
    rows = [json.loads(l) for l in manifest_path.read_text(encoding="utf-8").splitlines() if l.strip()]
    files = [CORPUS / r["local_path"] for r in rows]

    heading_counter = Counter()          # heading text -> total occurrences across all files
    heading_file_counter = Counter()     # heading text -> number of DISTINCT files it appears in
    file_lengths = []
    file_section_counts = []

    for p in files:
        if not p.exists():
            continue
        try:
            file_lengths.append(file_length(p))
            headings = extract_headings(p)
        except Exception:
            continue
        file_section_counts.append(len(headings))
        heading_counter.update(headings)
        for h in set(headings):
            heading_file_counter[h] += 1

    n_files = len(files)
    avg_len = statistics.mean(file_lengths) if file_lengths else 0
    avg_sections = statistics.mean(file_section_counts) if file_section_counts else 0

    qualifying = [
        h for h, cnt in heading_file_counter.items()
        if n_files > 0 and cnt / n_files >= STRUCTURED_MIN_FILE_SHARE
    ]
    form = "structured" if len(qualifying) >= STRUCTURED_MIN_HEADINGS else "prose"

    return {
        "id": source_id,
        "n_files": n_files,
        "avg_file_length_chars": round(avg_len),
        "avg_sections_per_file": round(avg_sections, 2),
        "form": form,
        "recurring_headings_for_form_call": sorted(
            qualifying, key=lambda h: -heading_file_counter[h]
        ),
        "top_headings": heading_counter.most_common(25),
        "heading_file_coverage": {
            h: heading_file_counter[h] for h, _ in heading_counter.most_common(25)
        },
    }


def render_markdown(probes: list[dict]) -> str:
    lines = []
    lines.append("# Structure probe")
    lines.append("")
    lines.append(
        "Stats only — no section-splitting, no cross-source taxonomy, no ingestion. "
        "Generated by `corpus/tools/structure_probe.py` over exactly the file set each "
        "source's manifest ended up with (`.md`/`.mdx` for git sources; raw, "
        "unconverted `.html` for web sources — headings there come from real `<h2>` "
        "tags, not markdown syntax)."
    )
    lines.append("")
    lines.append(
        "**Caveat on HTML sources (msio, fowler, anthropic, aws-wa's `.html` pages, sre):** "
        "raw HTML includes page chrome — nav bars, footers, \"related articles\", author "
        "bios, social-share widgets — which git sources never have (those are clean "
        "content-only `.md` files with no site wrapper). A `<h2>` in a footer counts the "
        "same as a `<h2>` in the article body here. Concretely: fowler's `form: structured` "
        "call below is driven by `Thoughtworks`/`about me`/`Topics`/`follow` — Fowler's "
        "site-wide sidebar, present on all ~900 pages — not by any real content template. "
        "Don't trust an HTML source's `structured` verdict without opening its top-headings "
        "table and checking whether the qualifying headings are actually content sections."
    )
    lines.append("")
    lines.append(
        f"\"structured\" vs \"prose\" heuristic: a source is called **structured** if at "
        f"least {STRUCTURED_MIN_HEADINGS} distinct H2 headings each appear in at least "
        f"{int(STRUCTURED_MIN_FILE_SHARE * 100)}% of that source's files (i.e. there's a "
        f"recognizable fixed template — Benefits/Drawbacks/When to use and similar). "
        f"Otherwise **prose** — tradeoffs are presumably embedded in running text with no "
        f"dedicated section, so this cutoff finding it there is coincidence, not template."
    )
    lines.append("")

    lines.append("## Summary")
    lines.append("")
    lines.append("| source | files | avg length (chars) | avg H2 sections/file | form |")
    lines.append("|---|---:|---:|---:|---|")
    for p in probes:
        lines.append(
            f"| {p['id']} | {p['n_files']} | {p['avg_file_length_chars']} | "
            f"{p['avg_sections_per_file']} | {p['form']} |"
        )
    lines.append("")

    structured = [p["id"] for p in probes if p["form"] == "structured"]
    prose = [p["id"] for p in probes if p["form"] == "prose"]
    lines.append(f"**Structured** ({len(structured)}): {', '.join(structured) or '(none)'}")
    lines.append("")
    lines.append(f"**Prose** ({len(prose)}): {', '.join(prose) or '(none)'}")
    lines.append("")

    for p in probes:
        lines.append(f"## {p['id']}")
        lines.append("")
        lines.append(
            f"- files: {p['n_files']}, avg length: {p['avg_file_length_chars']} chars, "
            f"avg H2 sections/file: {p['avg_sections_per_file']}"
        )
        lines.append(f"- form: **{p['form']}**")
        if p["recurring_headings_for_form_call"]:
            lines.append(
                f"- headings driving the '{p['form']}' call (appear in >= "
                f"{int(STRUCTURED_MIN_FILE_SHARE * 100)}% of files): "
                + ", ".join(f"`{h}`" for h in p["recurring_headings_for_form_call"])
            )
        lines.append("")
        lines.append("| H2 heading | total occurrences | files containing it |")
        lines.append("|---|---:|---:|")
        for h, cnt in p["top_headings"]:
            lines.append(f"| {h} | {cnt} | {p['heading_file_coverage'][h]} |")
        lines.append("")

    return "\n".join(lines)


def main():
    source_ids = sorted(p.stem for p in MANIFEST_DIR.glob("*.jsonl"))
    probes = [probe_source(sid) for sid in source_ids]
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(render_markdown(probes), encoding="utf-8")
    print(f"wrote {REPORT_PATH}")
    for p in probes:
        print(f"  {p['id']:12s} files={p['n_files']:5d} avg_len={p['avg_file_length_chars']:6d} "
              f"avg_sections={p['avg_sections_per_file']:5.2f} form={p['form']}")


if __name__ == "__main__":
    main()
